vim.keymap.set("n", "<leader>pv", ":Ex<cr>")
vim.keymap.set("n", "<leader>b", "<c-^>")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("v", "<", "<gv")
vim.keymap.set("v", ">", ">gv")
