return {
    "nvim-treesitter/nvim-treesitter",
    lazy = false,
    build = ":TSUpdate",
    config = function()
        local configs = require("nvim-treesitter.configs")
        configs.setup({
            ensure_installed = {
                "angular",
                "bash",
                "c",
                "cmake",
                "c_sharp",
                "css",
                "dockerfile",
                "git_config",
                "gitignore",
                "go",
                "gomod",
                "gotmpl",
                "gitignore",
                "hcl",
                "helm",
                "html",
                "java",
                "javascript",
                "json",
                "lua",
                "markdown",
                "nginx",
                "nix",
                "python",
                "query",
                "regex",
                "rust",
                "templ",
                "typescript",
                "vim",
                "vimdoc",
                "yaml",
            },
        })
    end,
}
